services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medical-clinic
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/medicalclinicdb
      SPRING_DATASOURCE_USERNAME: medicalclinic
      SPRING_DATASOURCE_PASSWORD: medicalclinic123
    ports:
      - "8080:8080"
  db:
    image: postgres
    container_name: medical-postgres
    environment:
      POSTGRES_DB: medicalclinicdb
      POSTGRES_USER: medicalclinic
      POSTGRES_PASSWORD: medicalclinic123
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    container_name: medical-pgadmin
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@wp.pl
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"