spring.application.name=medical-clinic
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/medicalclinicdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:medicalclinic}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:medicalclinic123}
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml